### ISSUE TITLE
Exception thrown when force-closing game

### ISSUE THREAD

**Issue by NillerMedDild** [Sunekaer/Simple-Discord-Rich-Presence#15]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2368

`SimpleDiscordRichPresence-1.16.4-1.3.5`

In the above report, a player experienced the game freezing, and force-closed it after a while. The logs contained a SDRP stacktrace so I thought I'd report it.

The player's world had reset when logging back in, but I doubt SDRP could be causing that :P

```
[23:09:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Enigmatica20210530T2029]'/minecraft:overworld
[23:09:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Enigmatica20210530T2029]'/minecraft:the_nether
[23:09:14] [Thread-62/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ArrayIndexOutOfBoundsException: 325
[23:09:14] [Thread-62/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.sunekaer.mods.sdrp.discord.discordipc.IPCClient.read(IPCClient.java:492)
[23:09:14] [Thread-62/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.sunekaer.mods.sdrp.discord.discordipc.IPCClient.lambda$startReading$0(IPCClient.java:367)
[23:09:14] [Thread-62/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.sunekaer.mods.sdrp.discord.discordipc.IPCClient$$Lambda$26490/832898523.run(Unknown Source)
[23:09:14] [Thread-62/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Sunekaer** [comment]
Hmm yeah nothing i can do about this, if I update this mode for 1.17 ill probably change lib.
